# Dataset Paths
root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean/train_downsampled'  # Update based on your dataset
data_dir: 'original'  # Choose from ['original', 'stylegan_256x256', 'vqvae']

# Synthesis-Specific Parameters
num_classes: 4  # Number of label conditions for synthesis
latent_dim: 64  # Optimized for CVAE
label_dim: 4  # Number of unique labels for conditional synthesis

# Training Hyperparameters
batch_size: 32  # Increased for more stable gradients
learning_rate: 0.00001  # Optimized for CVAE
# weight_decay: 0.0001  # Slightly increased regularization
num_epochs: 200  # CVAE benefits from longer training
early_stopping_patience: 20
pretrained: False  # Typically False for synthesis models since they’re trained from scratch
val_split: 0.2  # Fraction of data used for validation

# Model Selection
model_type: 'ddpm'  # Choose from ['ddpm', 'cvae']
# generator_arch: 'resnet'  # Options: ['mlp', 'cnn', 'resnet']

# Experiment Tracking
experiment_number: 1  # Update as needed
experiment_name: '013_Lightning_synthesis_DDPM_tryagainn'
model_dir: 'saved_models'  # Directory to save model checkpoints

# Evaluation & Logging
k_folds: 0  # 0 for holdout validation, increase for cross-validation
sanity_check: False
store_sample_per_epoch: True  # Save synthesized images per epoch
