# Dataset Paths
root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean/train_downsampled'  # Update based on your dataset
data_dir: 'original'  # Choose from ['original', 'stylegan_256x256', 'vqvae']

# Synthesis-Specific Parameters
label_dim: 4 #4  # Number of unique labels for conditional synthesis, set to 10 for mnist, 4 for embed
data_mode: 'embed' # embed
resize_dim: 64 # Resize data to 64x64

# Training Hyperparameters
batch_size: 8  # Increased for more stable gradients
learning_rate: 0.00001
num_epochs: 100  

# Model Configs

# Experiment Tracking
experiment_number: 1  # Update as needed
experiment_name: '029_DDPM_MONAI_256x256-progressive'
model_dir: 'saved_models'  # Directory to save model checkpoints

# Evaluation & Logging
sanity_check: False
store_sample_per_epoch: True  # Save synthesized images per epoch
