# Dataset Paths
# root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean_256x256/train'  # Update based on your dataset
root_dir: '/mnt/d/Datasets/EMBED/EMBED_binary_12vs56_256x256/train'
data_dir: 'original'

# Synthesis-Specific Parameters
drop_birads_3: True # probably benign is tough to classify
data_mode: 'embed' # embed
num_classes: 2
# resize_dim: 256 # Resize data

# Training Hyperparameters
model: GAN # GAN or DDPM
batch_size: 8  # Increased for more stable gradients, use 16 if also running evaluate.py otherwise 24
learning_rate: 0.00001
num_epochs: 50  
samples_per_class: 3676 # ignored if dynamic_balanced_sampling is True // Note that Malignant = 1148, or 1838 if both 5 and 6. Sample twice or thrice that.
dynamic_balanced_sampling: True
benign_to_malignant_ratio: 1.0 # for dynamic sampling, match how many benign per malignant for each epoch
## Benign: 3444
## Malignant: 1148

# Experiment Tracking
experiment_name: 'binary_11perepoch_12vs56'
# experiment_name: '044_DDPM_deeper_128x128' # use suffix and full existing name to continue from checkpoint

# Sanity checks
fast_dev_run: False