# Dataset Paths
# root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean/train_downsampled'
root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean_512x512/train_3221'  # Update based on your dataset
data_dir: 'original'

# Synthesis-Specific Parameters
label_dim: 4 #4  # Number of unique labels for conditional synthesis, set to 10 for mnist, 4 for embed
data_mode: 'embed' # embed
resize_dim: 256 # Resize data
conditional: True

# Training Hyperparameters
batch_size: 8  # Increased for more stable gradients
learning_rate: 0.00001
num_epochs: 100  

# Experiment Tracking
experiment_name: 'cDDPM_depth5_fixedScaling'
# experiment_name: '044_DDPM_deeper_128x128' # use suffix and full existing name to continue from checkpoint

# Evaluation & Logging
sanity_check: False
store_sample_per_epoch: True  # Save synthesized images per epoch
