# root_dir: '/mnt/c/Datasets/BCS-DBT-Szymon'
# root_dir: '/mnt/c/Datasets/SanityBCS_train'
# root_dir: '/mnt/c/Datasets/SanityCMMD_train'
# root_dir: '/mnt/c/Datasets/SanityDDSM_train'
# root_dir: '/mnt/c/Datasets/SanityThree_train'
root_dir: '/mnt/c/Datasets/ThreeDataDM_train'
data_dir: 'original' #'original' # 'stylegan_256x256', 'vqvae' , 'original'
# data_dir: 'original_sanity_subset' #'original' # 'stylegan_256x256', 'vqvae' , 'original'
batch_size: 24
learning_rate: 0.001
num_epochs: 100
pretrained: False
val_split: 0.2
resize_check: False
# resize_height: 256
# resize_width: 256
model_names:
  - resnet50
  # - simplecnn #an extremely simple model only for sanity
  - alexnet
  - efficientnet_b0
  - densenet121
  # - densenet169
  # - densenet201
  # - vgg16
  # - vgg19
k_folds: 0
sanity_check: True
store_sample_per_epoch: True # to visualize images
experiment_number: 23  # Add your experiment number here
# experiment_name: sanity_BCSdata 
# experiment_name: sanity_CMMDdata
# experiment_name: sanity_DDSMdata 
# experiment_name: sanity_Three
experiment_name: ThreeDataDM