# root_dir: '/mnt/d/Datasets/BCS-DBT-Szymon'
# root_dir: '/mnt/d/Datasets/SanityBCS_train'
# root_dir: '/mnt/d/Datasets/SanityCMMD_train'
# root_dir: '/mnt/d/Datasets/SanityDDSM_train'
# root_dir: '/mnt/d/Datasets/SanityInBreast_train'
# root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean_256x256/train'
# root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean_256x256_binary/train'
root_dir: '/mnt/d/Datasets/EMBED/EMBED_binary_12vs56_256x256/train'
data_dir: 'original' #'original' # 'stylegan_256x256', 'vqvae' , 'original'
synth_data_dir: 'synthetic_guide8.0'
real_percentage: 1.0 # use 0 for full synthetic, use 0.25, 0.5, 0.75 for mix

num_classes: 2 #

batch_size: 32
learning_rate: 0.001
weight_decay: 0.00001
early_stopping_patience: 20
num_epochs: 100
val_split: 0.2
# resize_height: 256
# resize_width: 256
model_name: resnet50
  # - efficientnet_b0
  # - densenet121
  # # - densenet169
  # # - densenet201
  # - vgg16
  # - vgg19
k_folds: 5 # 0 is hold out, increase for cross-validation, ideally 5
seed: 44
sanity_check: False
transform_check: basic # "basic" to just apply data preprocessing
store_sample_per_epoch: True # to visualize images
experiment_number: 62 # 62 onward is 12 vs 56
# --------60 # 48-53 we test four class. 55 to 60 we test binary, last experiment  full synthetic in each case (53 and 60)

experiment_name: binary_12vs56 # four_class_pretrainedImagenet_frozenlayers #binary_classification #
# experiment_name: sanity_EMBED_multi_class_CV
# experiment_name: ThreeDataDM_augmentations