# root_dir: '/mnt/d/Datasets/BCS-DBT-Szymon'
# root_dir: '/mnt/d/Datasets/SanityBCS_train'
# root_dir: '/mnt/d/Datasets/SanityCMMD_train'
# root_dir: '/mnt/d/Datasets/SanityDDSM_train'
# root_dir: '/mnt/d/Datasets/SanityInBreast_train'
# root_dir: '/mnt/d/Datasets/EMBED/EMBED_clean'
root_dir: '/mnt/d/Datasets/EMBED/sanity_EMBED'
data_dir: 'original' #'original' # 'stylegan_256x256', 'vqvae' , 'original'
# data_dir: 'original_sanity_subset' #'original' # 'stylegan_256x256', 'vqvae' , 'original'
num_classes: 4

batch_size: 24
learning_rate: 0.001
weight_decay: 0.00001
early_stopping_patience: 20
num_epochs: 100
pretrained: False
val_split: 0.2
# resize_height: 256
# resize_width: 256
model_names:
  - resnet50
  # - simplecnn #an extremely simple model only for sanity
  # - alexnet
  - efficientnet_b0
  - densenet121
  # - densenet169
  # - densenet201
  - vgg16
  # - vgg19
k_folds: 5 # 0 is hold out, increase for cross-validation, ideally 5
sanity_check: True
transform_check: basic # "basic" to just apply data preprocessing
store_sample_per_epoch: True # to visualize images
experiment_number: 33 # Add your experiment number here
# experiment_name: sanity_BCSdata 
# experiment_name: sanity_CMMDdata
# experiment_name: sanity_DDSMdata 
# experiment_name: sanity_inbreast
experiment_name: sanity_EMBED_multi_class_CV
# experiment_name: ThreeDataDM_augmentations