root_dir: '/mnt/c/Datasets/BCS-DBT-Szymon'
data_dir: 'vqvae' # 'stylegan', 'vqvae' , 'original'
batch_size: 32
learning_rate: 0.001
num_epochs: 10
val_split: 0.2
resize_height: 256
resize_width: 256
model_names:
  - resnet50
  - resnet101
  - densenet121
  - efficientnet_b0
  - vgg16
experiment_number: 1  # Add your experiment number here
