root_dir: '/mnt/c/Datasets/BCS-DBT-Szymon'
data_dir: 'vqvae' #'original_256x256' # 'stylegan_256x256', 'vqvae' , 'original'
batch_size: 32
learning_rate: 0.001
num_epochs: 30
val_split: 0.2
resize_check: False
# resize_height: 256
# resize_width: 256
model_names:
  - resnet50
  - densenet121
  - efficientnet_b0
  - vgg16
k_folds: 0
experiment_number: 3  # Add your experiment number here
experiment_name: holdout
